# Generated by Django 3.1.3 on 2020-11-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_nutrition_url_200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_nutrition_url_400',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url_400',
        ),
    ]
