# Generated by Django 3.1.3 on 2020-11-15 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'favorites'},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('substitute', 'product', 'user')},
        ),
    ]
