# Generated by Django 3.1.3 on 2020-11-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('favorites', '0003_auto_20201115_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_product', to='products.product'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_as_substitute', to='products.product'),
        ),
    ]
